<template>
    <AppLayout title="Invites">
        <div class="py-8 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-gray-50 via-indigo-50/30 to-purple-50/20 min-h-screen">
            <div class="max-w-7xl mx-auto space-y-8">
                <!-- Invites Management Card -->
                <div class="bg-white/70 backdrop-blur-md rounded-2xl shadow-xl border border-white/30 p-6 transition-all duration-300 hover:shadow-2xl animate-fade-slide">
                    <div class="flex items-center justify-between mb-6">
                        <div>
                            <h2 class="text-2xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                                Temporary Invites
                            </h2>
                            <p class="text-gray-500 text-sm mt-1">Manage temporary invitation links generated by users</p>
                        </div>
                        <div class="w-12 h-12 rounded-full bg-purple-100 flex items-center justify-center">
                            <svg class="w-6 h-6 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                            </svg>
                        </div>
                    </div>

                    <!-- Loading State -->
                    <div v-if="loading" class="flex flex-col items-center justify-center py-12">
                        <div class="relative w-12 h-12">
                            <div class="w-12 h-12 rounded-full border-4 border-indigo-50"></div>
                            <div class="w-12 h-12 rounded-full border-4 border-indigo-600 border-t-transparent animate-spin absolute top-0"></div>
                        </div>
                        <p class="mt-4 text-sm text-indigo-600 animate-pulse">Loading invites...</p>
                    </div>

                    <!-- Error State -->
                    <div v-else-if="error" class="text-center py-12 bg-red-50/50 rounded-xl border border-red-100">
                        <div class="text-red-500 font-semibold mb-2">{{ error }}</div>
                        <button @click="fetchInvites" class="mt-2 px-4 py-2 bg-red-100 text-red-700 rounded-lg hover:bg-red-200 transition">
                            ↻ Retry
                        </button>
                    </div>

                    <!-- Empty State -->
                    <div v-else-if="!invites.length" class="text-center py-12">
                        <svg class="w-20 h-20 mx-auto text-gray-300 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15 5v2m0 4v2m0 4v2M5 5a2 2 0 00-2 2v10a2 2 0 002 2h14a2 2 0 002-2V7a2 2 0 00-2-2H5z"></path>
                        </svg>
                        <p class="text-gray-400">No temporary invites found.</p>
                        <p class="text-sm text-gray-300 mt-1">Invites created by bot will appear here.</p>
                    </div>

                    <!-- Table Data -->
                    <div v-else class="overflow-x-auto rounded-xl border border-gray-100">
                        <table class="min-w-full divide-y divide-gray-200/50">
                            <thead class="bg-gradient-to-r from-indigo-50/50 to-purple-50/50">
                                <tr>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">Code</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">User ID</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">Expires At</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">Used</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">Created At</th>
                                    <th class="px-6 py-3 text-left text-xs font-semibold text-indigo-700 uppercase tracking-wider">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100 bg-white/50">
                                <tr v-for="inv in invites" :key="inv.id" class="hover:bg-indigo-50/30 transition duration-200">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-700">{{ truncateCode(inv.code) }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{{ inv.user_id }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{{ formatDate(inv.expires_at) }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <span :class="inv.used ? 'bg-red-100 text-red-700' : 'bg-green-100 text-green-700'" class="px-2 py-1 rounded-full text-xs font-semibold">
                                            {{ inv.used ? 'Used' : 'Active' }}
                                        </span>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ formatDate(inv.created_at) }}</td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        <button @click="deleteInvite(inv.id)" class="text-red-500 hover:text-red-700 transition-colors" title="Delete invite">
                                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                            </svg>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </AppLayout>
</template>

<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import { ref, onMounted } from 'vue';
import axios from 'axios';

const invites = ref([]);
const loading = ref(false);
const error = ref(null);

async function fetchInvites() {
    loading.value = true;
    error.value = null;
    try {
        const res = await axios.get('/api/invites');
        invites.value = res.data;
    } catch (err) {
        error.value = 'Failed to load invites. Please try again.';
        console.error(err);
    } finally {
        loading.value = false;
    }
}

async function deleteInvite(id) {
    if (!confirm('Are you sure you want to delete this invite?')) return;
    try {
        await axios.delete(`/api/invites/${id}`);
        await fetchInvites();
    } catch (err) {
        alert('Failed to delete invite.');
    }
}

function formatDate(dateString) {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleString();
}

function truncateCode(code) {
    if (!code) return '-';
    return code.length > 16 ? code.substring(0, 14) + '...' : code;
}

onMounted(fetchInvites);
</script>

<style scoped>
@keyframes fadeSlide {
    from {
        opacity: 0;
        transform: translateY(20px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}
.animate-fade-slide {
    animation: fadeSlide 0.5s ease-out forwards;
}
</style>